#!/bin/sh -e

. ci/travis/lib.sh
. ci/travis/before_install_lib.sh

BOOST_PACKAGES_BASE="libboost libboost-regex libboost-date-time
	libboost-program-options libboost-test libboost-filesystem
	libboost-system libboost-thread"

handle_centos() {
	# First EPEL stuff
	yum install -y epel-release

	yum -y groupinstall 'Development Tools'
	# FIXME: remove python-mako & python-six when not building gnuradio
	yum -y install cmake boost-devel python-devel fftw-devel bison flex yum \
		python-mako python-six \
		swig git libusb1-devel doxygen libaio-devel avahi-devel bzip2 gzip \
		rpm rpm-build libxml2-devel

	yum remove cmake -y
	wget -c "https://cmake.org/files/v3.17/cmake-3.17.2.tar.gz"
	tar -zxvf cmake-3.17.2.tar.gz
	cd cmake-3.17.2
	./bootstrap
	make -j $(nproc)
	make install -j $(nproc)
	cd ..
	
	__handle_common

	if [ "$TRAVIS" = "true" ] || [ "$INSIDE_DOCKER" = "1" ] ; then
		for pkg in libiio libad9361-iio ; do
			wget http://swdownloads.analog.com/cse/travis_builds/${LIBIIO_BRANCH}_latest_${pkg}${LDIST}.rpm
			sudo yum localinstall -y ./${LIBIIO_BRANCH}_latest_${pkg}${LDIST}.rpm
		done
	fi
}

handle_centos_docker() {
	prepare_docker_image "centos:centos${OS_VERSION}"
}

handle_ubuntu_docker() {
	prepare_docker_image "ubuntu:${OS_VERSION}"
}

handle_default() {
	local BOOST_PACKAGES

	for package in $BOOST_PACKAGES_BASE ; do
		BOOST_PACKAGES="$BOOST_PACKAGES ${package}${BOOST_VER}-dev"
	done

	sudo apt-get -qq update
	
	ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
	export DEBIAN_FRONTEND=noninteractive
	apt-get install -y tzdata
	dpkg-reconfigure --frontend noninteractive tzdata

	sudo apt-get upgrade -y
	# FIXME: remove python-mako & python-six when not building gnuradio
	sudo apt-get install -y build-essential libboost-dev libpython-dev bison \
		flex git libfftw3-dev swig cmake libaio-dev libavahi-client-dev libavahi-common-dev \
		libusb-1.0-0-dev libxml2-dev tar bzip2 gzip \
		python-mako python-six \
		$BOOST_PACKAGES
		
	# Requirements to build gnuradio 3.8
	sudo apt-get install -y git cmake g++ libboost-all-dev libgmp-dev swig python3-numpy \
		python3-mako python3-sphinx python3-lxml doxygen libfftw3-dev \
		libsdl1.2-dev libgsl-dev libqwt-qt5-dev libqt5opengl5-dev python3-pyqt5 \
		liblog4cpp5-dev libzmq3-dev python3-yaml python3-click python3-click-plugins \
		python3-zmq python3-scipy

	if apt-cache show libserialport-dev &> /dev/null ; then
		sudo apt-get install -y libserialport-dev
	fi

	__handle_common

	if [ "$TRAVIS" = "true" ] || [ "$INSIDE_DOCKER" = "1" ] ; then
		for pkg in libiio libad9361-iio ; do
			wget http://swdownloads.analog.com/cse/travis_builds/${LIBIIO_BRANCH}_latest_${pkg}${LDIST}.deb
			sudo dpkg -i ./${LIBIIO_BRANCH}_latest_${pkg}${LDIST}.deb
		done
	fi
}

LIBNAME="gr-iio"
OS_TYPE=${1:-default}
OS_VERSION="$2"

handle_${OS_TYPE}
